### Restart and Run All

In [1]:
import calendar
import os
import pandas as pd
import panel as pn

from datetime import date, timedelta
from sqlalchemy import create_engine

pn.extension('tabulator')

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
box_path = "\\Users\\User\\Dropbox\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

today = date.today()
today

datetime.date(2023, 6, 25)

### Create Price-for-Order.csv

In [2]:
sql = """
SELECT trade, name, qty, price AS target, active, reason, market, xdate 
FROM orders
ORDER BY trade, name"""
orders = pd.read_sql(sql, conlite)
orders

   trade     name    qty  target  active    reason  market       xdate
0      B    BANPU   3000    7.80       0   RD30pct   SET50  2023-04-10
1      B      BBL    200  125.00       0             SET50  2023-04-21
2      B     BDMS   1000   24.00       0       XXX   SET50  2022-12-22
3      B      BEM   2500    7.80       0      52WL   SET50  2022-12-22
4      B       BH    200  169.00       0      5pct   SET50  2022-12-22
5      B  CPNREIT   5000   10.20       0      5pct     SET  2023-05-23
6      B      DIF   2000   10.30       0      5pct     SET  2023-05-15
7      B       EA    400   61.00       0      52WL   SET50  2022-12-22
8      B      FPT   1500   13.65       0               SET  2022-12-22
9      B    JMART   1200   17.00       0      5pct   SET50  2023-04-11
10     B      JMT   1800   51.00       0      5pct   SET50  2023-04-11
11     B      KKP    500   58.00       0            SET100  2023-04-28
12     B      KTB   1500   14.30       0             SET50  2023-04-20
13     B    LANNA   1500   13.80       0               SET  2023-03-18
14     B     LHFG  20000    1.00       0               SET  2022-12-22
15     B      MCS   3000    7.00       0   RD50pct     SET  2023-03-17
16     B      NER   5000    4.54       0   RD40pct     SET  2023-04-20
17     B    OISHI    500   42.50       0               SET  2022-12-22
18     B      ORI   3000   10.00       0      52WL  SET100  2023-05-08
19     B      PTG   1800   11.40       0            SET100  2022-12-22
20     B    PTTEP    200  134.50       0             SET50  2023-02-14
21     B   SINGER   2000   10.40       0   RD60pct  SET100  2023-05-03
22     B      STA   1200   18.30       0   RD50pct  SET100  2023-04-19
23     B    SYNEX   3000   12.50       0  RND55pct     SET  2023-03-09
24     B    TASCO   1500   15.60       0       XXX     SET  2022-12-22
25     B    TFFIF  10000    7.65       0       DOS     SET  2023-05-31
26     B      TMT   3000    7.60       0   RD25pct     SET  2023-04-18
27     B      TTB  20000    1.09       0      52WL   SET50  2023-04-18
28     S       AH   1200   39.00       0      5pct     SET  2022-12-22
29     S      AWC   9000    5.20       0      5pct   SET50  2022-12-22
30     S      BCH   3000   22.40       0      5pct  SET100  2023-05-09
31     S   GVREIT  10000    9.10       0      5pct     SET  2023-05-26
32     S     ICHI   1500   15.00       0      5pct     SET  2022-12-22
33     S      IVL   2400   37.75       0      5pct   SET50  2023-05-26
34     S    JASIF  10000    7.50       0       CUT     SET  2023-05-19
35     S      KTC    900   52.50       0      5pct   SET50  2022-12-22
36     S    PTTGC    600   53.25       0   RD45pct   SET50  2023-02-27
37     S     SENA  15000    4.50       0     C4.48     SET  2023-05-11

### Price-Today is created from Daily/205 - Create Price Data from Excel files

In [3]:
file_name = "Price-Today.csv"
input_file = data_path + file_name
prices = pd.read_csv(input_file)
prices

,name,date,price,change,%change,open,high,low,volume,value(m)
0,ACE,2023-06-23,1.89,-0.02,-1.047120,1.91,1.92,1.88,15610982,29631.01586
1,ADVANC,2023-06-23,211.00,-1.00,-0.471698,211.00,213.00,209.00,4423809,933654.78400
2,AEONTS,2023-06-23,186.00,-4.00,-2.105263,190.00,190.50,185.50,213604,40005.98350
3,AH,2023-06-23,32.25,-1.00,-3.007519,33.00,33.00,32.25,2130807,69306.26100
4,AIE,2023-06-23,1.44,0.01,0.699301,1.42,1.44,1.42,212273,302.73027
...,...,...,...,...,...,...,...,...,...,...
187,WHAIR,2023-06-23,7.20,0.00,0.000000,7.25,7.25,7.15,271400,1949.18500
188,WHART,2023-06-23,10.60,0.10,0.952381,10.40,10.70,10.40,2918600,30662.58040
189,WHAUP,2023-06-23,3.74,-0.02,-0.531915,3.76,3.78,3.72,837232,3132.20272
190,WICE,2023-06-23,8.45,0.00,0.000000,8.45,8.55,8.35,937825,7918.56665
191,WORK,2023-06-23,14.90,-0.50,-3.246753,15.30,15.40,14.90,586178,8812.37880

In [4]:
df_merge  = pd.merge(orders, prices, on = 'name', how='inner')
df_merge

,trade,name,qty,target,active,reason,market,xdate,date,price,change,%change,open,high,low,volume,value(m)
0,B,BANPU,3000,7.80,0,RD30pct,SET50,2023-04-10,2023-06-23,9.15,0.05,0.549451,9.10,9.15,9.05,47159009,4.291027e+05
1,B,BBL,200,125.00,0,,SET50,2023-04-21,2023-06-23,163.00,0.00,0.000000,163.00,164.00,162.50,2594954,4.229433e+05
2,B,BDMS,1000,24.00,0,XXX,SET50,2022-12-22,2023-06-23,28.25,-0.25,-0.877193,28.50,28.75,28.25,39098219,1.113050e+06
3,B,BEM,2500,7.80,0,52WL,SET50,2022-12-22,2023-06-23,8.30,-0.10,-1.190476,8.35,8.35,8.10,32695773,2.686467e+05
4,B,BH,200,169.00,0,5pct,SET50,2022-12-22,2023-06-23,228.00,-4.00,-1.724138,230.00,231.00,227.00,1538303,3.516142e+05
5,B,CPNREIT,5000,10.20,0,5pct,SET,2023-05-23,2023-06-23,11.00,0.60,5.769231,10.40,11.00,10.20,4383653,4.714373e+04
6,B,DIF,2000,10.30,0,5pct,SET,2023-05-15,2023-06-23,10.60,-0.20,-1.851852,10.60,10.70,10.00,141537791,1.475395e+06
7,B,EA,400,61.00,0,52WL,SET50,2022-12-22,2023-06-23,58.00,1.00,1.754386,57.00,58.50,56.75,7510582,4.349452e+05
8,B,JMART,1200,17.00,0,5pct,SET50,2023-04-11,2023-06-23,16.00,-0.10,-0.621118,16.20,16.50,15.80,15215746,2.448863e+05
9,B,JMT,1800,51.00,0,5pct,SET50,2023-04-11,2023-06-23,36.75,-0.25,-0.675676,37.00,37.50,36.25,10632690,3.917201e+05
10,B,KKP,500,58.00,0,,SET100,2023-04-28,2023-06-23,60.00,0.25,0.418410,60.00,60.50,59.50,1856175,1.113546e+05
11,B,KTB,1500,14.30,0,,SET50,2023-04-20,2023-06-23,19.40,-0.10,-0.512821,19.50,19.50,19.30,14694795,2.852266e+05
12,B,LANNA,1500,13.80,0,,SET,2023-03-18,2023-06-23,15.50,0.40,2.649007,15.20,15.60,15.00,1856092,2.848993e+04
13,B,MCS,3000,7.00,0,RD50pct,SET,2023-03-17,2023-06-23,6.75,0.00,0.000000,6.80,6.80,6.55,691459,4.623915e+03
14,B,NER,5000,4.54,0,RD40pct,SET,2023-04-20,2023-06-23,4.66,-0.04,-0.851064,4.68,4.68,4.64,2888481,1.346011e+04
15,B,ORI,3000,10.00,0,52WL,SET100,2023-05-08,2023-06-23,10.60,-0.10,-0.934579,10.60,10.70,10.40,4009213,4.232357e+04
16,B,PTG,1800,11.40,0,,SET100,2022-12-22,2023-06-23,11.60,-0.10,-0.854701,11.70,11.70,11.30,5446770,6.284360e+04
17,B,PTTEP,200,134.50,0,,SET50,2023-02-14,2023-06-23,149.00,0.00,0.000000,147.00,150.50,146.00,5386317,7.982319e+05
18,B,SINGER,2000,10.40,0,RD60pct,SET100,2023-05-03,2023-06-23,9.85,-0.10,-1.005025,9.90,10.10,9.75,5246769,5.191748e+04
19,B,STA,1200,18.30,0,RD50pct,SET100,2023-04-19,2023-06-23,17.10,-0.50,-2.840909,17.60,17.60,17.00,5556163,9.583450e+04
20,B,SYNEX,3000,12.50,0,RND55pct,SET,2023-03-09,2023-06-23,12.60,-0.10,-0.787402,12.70,12.90,12.50,252861,3.215710e+03
21,B,TASCO,1500,15.60,0,XXX,SET,2022-12-22,2023-06-23,18.40,-0.30,-1.604278,18.90,18.90,18.40,2919732,5.419202e+04
22,B,TFFIF,10000,7.65,0,DOS,SET,2023-05-31,2023-06-23,7.70,0.10,1.315789,7.65,7.70,7.55,2910530,2.220558e+04
23,B,TMT,3000,7.60,0,RD25pct,SET,2023-04-18,2023-06-23,7.35,0.00,0.000000,7.35,7.40,7.25,166230,1.215851e+03
24,B,TTB,20000,1.09,0,52WL,SET50,2023-04-18,2023-06-23,1.58,-0.01,-0.628931,1.58,1.59,1.55,391995473,6.171016e+05
25,S,AH,1200,39.00,0,5pct,SET,2022-12-22,2023-06-23,32.25,-1.00,-3.007519,33.00,33.00,32.25,2130807,6.930626e+04
26,S,AWC,9000,5.20,0,5pct,SET50,2022-12-22,2023-06-23,4.88,-0.02,-0.408163,4.88,4.90,4.80,21918900,1.063487e+05
27,S,BCH,3000,22.40,0,5pct,SET100,2023-05-09,2023-06-23,17.60,-0.10,-0.564972,17.70,17.70,17.50,9315686,1.638113e+05
28,S,GVREIT,10000,9.10,0,5pct,SET,2023-05-26,2023-06-23,8.45,-0.10,-1.169591,8.50,8.60,8.45,247202,2.095152e+03
29,S,ICHI,1500,15.00,0,5pct,SET,2022-12-22,2023-06-23,14.10,0.00,0.000000,14.10,14.30,13.90,4376808,6.174917e+04
30,S,IVL,2400,37.75,0,5pct,SET50,2023-05-26,2023-06-23,34.25,0.00,0.000000,34.00,34.75,33.75,4801930,1.646457e+05
31,S,JASIF,10000,7.50,0,CUT,SET,2023-05-19,2023-06-23,7.10,-0.05,-0.699301,7.05,7.15,7.05,8147656,5.783905e+04
32,S,KTC,900,52.50,0,5pct,SET50,2022-12-22,2023-06-23,50.50,0.25,0.497512,50.00,50.50,49.75,1835414,9.218202e+04
33,S,PTTGC,600,53.25,0,RD45pct,SET50,2023-02-27,2023-06-23,37.25,0.00,0.000000,37.00,37.75,36.75,4583820,1.709937e+05
34,S,SENA,15000,4.50,0,C4.48,SET,2023-05-11,2023-06-23,3.02,-0.04,-1.307190,3.06,3.06,2.98,1376341,4.137243e+03

In [5]:
df_merge['spd'] = 0

In [6]:
colo = ['trade', 'name', 'spd', 'reason', 'market', 'qty', 'target', 'price', 'change', '%change',
        'active', 'xdate']
df_merge[colo]

,trade,name,spd,reason,market,qty,target,price,change,%change,active,xdate
0,B,BANPU,0,RD30pct,SET50,3000,7.80,9.15,0.05,0.549451,0,2023-04-10
1,B,BBL,0,,SET50,200,125.00,163.00,0.00,0.000000,0,2023-04-21
2,B,BDMS,0,XXX,SET50,1000,24.00,28.25,-0.25,-0.877193,0,2022-12-22
3,B,BEM,0,52WL,SET50,2500,7.80,8.30,-0.10,-1.190476,0,2022-12-22
4,B,BH,0,5pct,SET50,200,169.00,228.00,-4.00,-1.724138,0,2022-12-22
5,B,CPNREIT,0,5pct,SET,5000,10.20,11.00,0.60,5.769231,0,2023-05-23
6,B,DIF,0,5pct,SET,2000,10.30,10.60,-0.20,-1.851852,0,2023-05-15
7,B,EA,0,52WL,SET50,400,61.00,58.00,1.00,1.754386,0,2022-12-22
8,B,JMART,0,5pct,SET50,1200,17.00,16.00,-0.10,-0.621118,0,2023-04-11
9,B,JMT,0,5pct,SET50,1800,51.00,36.75,-0.25,-0.675676,0,2023-04-11
10,B,KKP,0,,SET100,500,58.00,60.00,0.25,0.418410,0,2023-04-28
11,B,KTB,0,,SET50,1500,14.30,19.40,-0.10,-0.512821,0,2023-04-20
12,B,LANNA,0,,SET,1500,13.80,15.50,0.40,2.649007,0,2023-03-18
13,B,MCS,0,RD50pct,SET,3000,7.00,6.75,0.00,0.000000,0,2023-03-17
14,B,NER,0,RD40pct,SET,5000,4.54,4.66,-0.04,-0.851064,0,2023-04-20
15,B,ORI,0,52WL,SET100,3000,10.00,10.60,-0.10,-0.934579,0,2023-05-08
16,B,PTG,0,,SET100,1800,11.40,11.60,-0.10,-0.854701,0,2022-12-22
17,B,PTTEP,0,,SET50,200,134.50,149.00,0.00,0.000000,0,2023-02-14
18,B,SINGER,0,RD60pct,SET100,2000,10.40,9.85,-0.10,-1.005025,0,2023-05-03
19,B,STA,0,RD50pct,SET100,1200,18.30,17.10,-0.50,-2.840909,0,2023-04-19
20,B,SYNEX,0,RND55pct,SET,3000,12.50,12.60,-0.10,-0.787402,0,2023-03-09
21,B,TASCO,0,XXX,SET,1500,15.60,18.40,-0.30,-1.604278,0,2022-12-22
22,B,TFFIF,0,DOS,SET,10000,7.65,7.70,0.10,1.315789,0,2023-05-31
23,B,TMT,0,RD25pct,SET,3000,7.60,7.35,0.00,0.000000,0,2023-04-18
24,B,TTB,0,52WL,SET50,20000,1.09,1.58,-0.01,-0.628931,0,2023-04-18
25,S,AH,0,5pct,SET,1200,39.00,32.25,-1.00,-3.007519,0,2022-12-22
26,S,AWC,0,5pct,SET50,9000,5.20,4.88,-0.02,-0.408163,0,2022-12-22
27,S,BCH,0,5pct,SET100,3000,22.40,17.60,-0.10,-0.564972,0,2023-05-09
28,S,GVREIT,0,5pct,SET,10000,9.10,8.45,-0.10,-1.169591,0,2023-05-26
29,S,ICHI,0,5pct,SET,1500,15.00,14.10,0.00,0.000000,0,2022-12-22
30,S,IVL,0,5pct,SET50,2400,37.75,34.25,0.00,0.000000,0,2023-05-26
31,S,JASIF,0,CUT,SET,10000,7.50,7.10,-0.05,-0.699301,0,2023-05-19
32,S,KTC,0,5pct,SET50,900,52.50,50.50,0.25,0.497512,0,2022-12-22
33,S,PTTGC,0,RD45pct,SET50,600,53.25,37.25,0.00,0.000000,0,2023-02-27
34,S,SENA,0,C4.48,SET,15000,4.50,3.02,-0.04,-1.307190,0,2023-05-11

In [7]:
file_name = "Price-for-Order.csv"
output_file = data_path + file_name
osd_file = osd_path + file_name

df_merge[colo].to_csv(output_file, header=True, index=False)
df_merge[colo].to_csv(osd_file, header=True, index=False)

### End of Create Price-for-Order

In [8]:
%pwd

'C:\\Users\\User\\OneDrive\\A7\\Weekly'

In [9]:
os.chdir("C:\\users\\user\\onedrive\\a7")
%pwd

'C:\\users\\user\\onedrive\\a7'

### From Price-for-Order convert into orders-log with spread & active

In [10]:
!ruby ruby\\order-log-new.rb

trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
B,BANPU,-27,RD30pct,SET50,3000,7.8,9.15,0.05,0.549451,0,2023-04-10
B,BBL,-76,,SET50,200,125.0,163.0,0.0,0.0,0,2023-04-21
B,BDMS,-23,XXX,SET50,1000,24.0,28.25,-0.25,-0.877193,0,2022-12-22
B,BEM,-10,52WL,SET50,2500,7.8,8.3,-0.1,-1.190476,0,2022-12-22
B,BH,-90,5pct,SET50,200,169.0,228.0,-4.0,-1.724138,0,2022-12-22
B,CPNREIT,-8,5pct,SET,5000,10.2,11.0,0.6,5.769231,1,2023-05-23
B,DIF,-3,5pct,SET,2000,10.3,10.6,-0.2,-1.851852,1,2023-05-15
B,EA,12,52WL,SET50,400,61.0,58.0,1.0,1.754386,0,2022-12-22
B,JMART,10,5pct,SET50,1200,17.0,16.0,-0.1,-0.621118,0,2023-04-11
B,JMT,57,5pct,SET50,1800,51.0,36.75,-0.25,-0.675676,0,2023-04-11
B,KKP,-8,,SET100,500,58.0,60.0,0.25,0.41841,1,2023-04-28
B,KTB,-51,,SET50,1500,14.3,19.4,-0.1,-0.512821,0,2023-04-20
B,LANNA,-17,,SET,1500,13.8,15.5,0.4,2.649007,0,2023-03-18
B,MCS,5,RD50pct,SET,3000,7.0,6.75,0.0,0.0,1,2023-03-17
B,NER,-6,RD40pct,SET,5000,4.54,4.66,-0.04,-0.851064,1,2023-04-20
B,ORI,-6,52WL,SET100,3000,10.0,10.6,-0.1,-0.934579,1,2023-05-08
B,PTG,-2,,SET100,1800,11.4,11.6,-0.1,-0.854701,1,2022-12-22
B,PTTEP,-29,,SET50,200,134.5,149.0,0.0,0.0,0,2023-02-14
B,SINGER,7,RD60pct,SET100,2000,10.4,9.85,-0.1,-1.005025,1,2023-05-03
B,STA,12,RD50pct,SET100,1200,18.3,17.1,-0.5,-2.840909,0,2023-04-19
B,SYNEX,-1,RND55pct,SET,3000,12.5,12.6,-0.1,-0.787402,1,2023-03-09
B,TASCO,-28,XXX,SET,1500,15.6,18.4,-0.3,-1.604278,0,2022-12-22
B,TFFIF,-1,DOS,SET,10000,7.65,7.7,0.1,1.315789,1,2023-05-31
B,TMT,5,RD25pct,SET,3000,7.6,7.35,0.0,0.0,1,2023-04-18
B,TTB,-49,52WL,SET50,20000,1.09,1.58,-0.01,-0.628931,0,2023-04-18
S,AH,27,5pct,SET,1200,39.0,32.25,-1.0,-3.007519,0,2022-12-22
S,AWC,10,5pct,SET50,9000,5.2,4.88,-0.02,-0.408163,0,2022-12-22
S,BCH,48,5pct,SET100,3000,22.4,17.6,-0.1,-0.564972,0,2023-05-09
S,GVREIT,13,5pct,SET,10000,9.1,8.45,-0.1,-1.169591,0,2023-05-26
S,ICHI,9,5pct,SET,1500,15.0,14.1,0.0,0.0,1,2022-12-22
S,IVL,14,5pct,SET50,2400,37.75,34.25,0.0,0.0,0,2023-05-26
S,JASIF,8,CUT,SET,10000,7.5,7.1,-0.05,-0.699301,1,2023-05-19
S,KTC,8,5pct,SET50,900,52.5,50.5,0.25,0.497512,1,2022-12-22
S,PTTGC,64,RD45pct,SET50,600,53.25,37.25,0.0,0.0,0,2023-02-27
S,SENA,74,C4.48,SET,15000,4.5,3.02,-0.04,-1.30719,0,2023-05-11

In [11]:
os.chdir("C:\\users\\user\\onedrive\\a7\\weekly")
%pwd

'C:\\users\\user\\onedrive\\a7\\weekly'

In [12]:
file_name   = 'orders-log.csv'
input_file = data_path + file_name
#col_names   = ['trade','name','spreads','reason','market','qty','target_price','set_price','chg_amt','chg_pct','active']
df_log = pd.read_csv(input_file, sep=',',  index_col=None)
df_log

,trade,name,spd,reason,market,qty,target,current,change,%change,active,xdate
0,B,BANPU,-27,RD30pct,SET50,3000,7.80,9.15,0.05,0.549451,0,2023-04-10
1,B,BBL,-76,NaN,SET50,200,125.00,163.00,0.00,0.000000,0,2023-04-21
2,B,BDMS,-23,XXX,SET50,1000,24.00,28.25,-0.25,-0.877193,0,2022-12-22
3,B,BEM,-10,52WL,SET50,2500,7.80,8.30,-0.10,-1.190476,0,2022-12-22
4,B,BH,-90,5pct,SET50,200,169.00,228.00,-4.00,-1.724138,0,2022-12-22
5,B,CPNREIT,-8,5pct,SET,5000,10.20,11.00,0.60,5.769231,1,2023-05-23
6,B,DIF,-3,5pct,SET,2000,10.30,10.60,-0.20,-1.851852,1,2023-05-15
7,B,EA,12,52WL,SET50,400,61.00,58.00,1.00,1.754386,0,2022-12-22
8,B,JMART,10,5pct,SET50,1200,17.00,16.00,-0.10,-0.621118,0,2023-04-11
9,B,JMT,57,5pct,SET50,1800,51.00,36.75,-0.25,-0.675676,0,2023-04-11
10,B,KKP,-8,NaN,SET100,500,58.00,60.00,0.25,0.418410,1,2023-04-28
11,B,KTB,-51,NaN,SET50,1500,14.30,19.40,-0.10,-0.512821,0,2023-04-20
12,B,LANNA,-17,NaN,SET,1500,13.80,15.50,0.40,2.649007,0,2023-03-18
13,B,MCS,5,RD50pct,SET,3000,7.00,6.75,0.00,0.000000,1,2023-03-17
14,B,NER,-6,RD40pct,SET,5000,4.54,4.66,-0.04,-0.851064,1,2023-04-20
15,B,ORI,-6,52WL,SET100,3000,10.00,10.60,-0.10,-0.934579,1,2023-05-08
16,B,PTG,-2,NaN,SET100,1800,11.40,11.60,-0.10,-0.854701,1,2022-12-22
17,B,PTTEP,-29,NaN,SET50,200,134.50,149.00,0.00,0.000000,0,2023-02-14
18,B,SINGER,7,RD60pct,SET100,2000,10.40,9.85,-0.10,-1.005025,1,2023-05-03
19,B,STA,12,RD50pct,SET100,1200,18.30,17.10,-0.50,-2.840909,0,2023-04-19
20,B,SYNEX,-1,RND55pct,SET,3000,12.50,12.60,-0.10,-0.787402,1,2023-03-09
21,B,TASCO,-28,XXX,SET,1500,15.60,18.40,-0.30,-1.604278,0,2022-12-22
22,B,TFFIF,-1,DOS,SET,10000,7.65,7.70,0.10,1.315789,1,2023-05-31
23,B,TMT,5,RD25pct,SET,3000,7.60,7.35,0.00,0.000000,1,2023-04-18
24,B,TTB,-49,52WL,SET50,20000,1.09,1.58,-0.01,-0.628931,0,2023-04-18
25,S,AH,27,5pct,SET,1200,39.00,32.25,-1.00,-3.007519,0,2022-12-22
26,S,AWC,10,5pct,SET50,9000,5.20,4.88,-0.02,-0.408163,0,2022-12-22
27,S,BCH,48,5pct,SET100,3000,22.40,17.60,-0.10,-0.564972,0,2023-05-09
28,S,GVREIT,13,5pct,SET,10000,9.10,8.45,-0.10,-1.169591,0,2023-05-26
29,S,ICHI,9,5pct,SET,1500,15.00,14.10,0.00,0.000000,1,2022-12-22
30,S,IVL,14,5pct,SET50,2400,37.75,34.25,0.00,0.000000,0,2023-05-26
31,S,JASIF,8,CUT,SET,10000,7.50,7.10,-0.05,-0.699301,1,2023-05-19
32,S,KTC,8,5pct,SET50,900,52.50,50.50,0.25,0.497512,1,2022-12-22
33,S,PTTGC,64,RD45pct,SET50,600,53.25,37.25,0.00,0.000000,0,2023-02-27
34,S,SENA,74,C4.48,SET,15000,4.50,3.02,-0.04,-1.307190,0,2023-05-11

In [13]:
df_log.groupby('active')['trade'].count()

active
0    21
1    14
Name: trade, dtype: int64

In [14]:
sql = '''
DELETE FROM orders'''
rp = conlite.execute(sql)
rp.rowcount

39

In [15]:
colt = 'trade name qty target active reason market xdate'.split()
final = df_log[colt]
final

   trade     name    qty  target  active    reason  market       xdate
0      B    BANPU   3000    7.80       0   RD30pct   SET50  2023-04-10
1      B      BBL    200  125.00       0       NaN   SET50  2023-04-21
2      B     BDMS   1000   24.00       0       XXX   SET50  2022-12-22
3      B      BEM   2500    7.80       0      52WL   SET50  2022-12-22
4      B       BH    200  169.00       0      5pct   SET50  2022-12-22
5      B  CPNREIT   5000   10.20       1      5pct     SET  2023-05-23
6      B      DIF   2000   10.30       1      5pct     SET  2023-05-15
7      B       EA    400   61.00       0      52WL   SET50  2022-12-22
8      B    JMART   1200   17.00       0      5pct   SET50  2023-04-11
9      B      JMT   1800   51.00       0      5pct   SET50  2023-04-11
10     B      KKP    500   58.00       1       NaN  SET100  2023-04-28
11     B      KTB   1500   14.30       0       NaN   SET50  2023-04-20
12     B    LANNA   1500   13.80       0       NaN     SET  2023-03-18
13     B      MCS   3000    7.00       1   RD50pct     SET  2023-03-17
14     B      NER   5000    4.54       1   RD40pct     SET  2023-04-20
15     B      ORI   3000   10.00       1      52WL  SET100  2023-05-08
16     B      PTG   1800   11.40       1       NaN  SET100  2022-12-22
17     B    PTTEP    200  134.50       0       NaN   SET50  2023-02-14
18     B   SINGER   2000   10.40       1   RD60pct  SET100  2023-05-03
19     B      STA   1200   18.30       0   RD50pct  SET100  2023-04-19
20     B    SYNEX   3000   12.50       1  RND55pct     SET  2023-03-09
21     B    TASCO   1500   15.60       0       XXX     SET  2022-12-22
22     B    TFFIF  10000    7.65       1       DOS     SET  2023-05-31
23     B      TMT   3000    7.60       1   RD25pct     SET  2023-04-18
24     B      TTB  20000    1.09       0      52WL   SET50  2023-04-18
25     S       AH   1200   39.00       0      5pct     SET  2022-12-22
26     S      AWC   9000    5.20       0      5pct   SET50  2022-12-22
27     S      BCH   3000   22.40       0      5pct  SET100  2023-05-09
28     S   GVREIT  10000    9.10       0      5pct     SET  2023-05-26
29     S     ICHI   1500   15.00       1      5pct     SET  2022-12-22
30     S      IVL   2400   37.75       0      5pct   SET50  2023-05-26
31     S    JASIF  10000    7.50       1       CUT     SET  2023-05-19
32     S      KTC    900   52.50       1      5pct   SET50  2022-12-22
33     S    PTTGC    600   53.25       0   RD45pct   SET50  2023-02-27
34     S     SENA  15000    4.50       0     C4.48     SET  2023-05-11

In [16]:
rcds = final.values.tolist()
rcds

[['B', 'BANPU', 3000, 7.8, 0, 'RD30pct', 'SET50', '2023-04-10'],
 ['B', 'BBL', 200, 125.0, 0, nan, 'SET50', '2023-04-21'],
 ['B', 'BDMS', 1000, 24.0, 0, 'XXX', 'SET50', '2022-12-22'],
 ['B', 'BEM', 2500, 7.8, 0, '52WL', 'SET50', '2022-12-22'],
 ['B', 'BH', 200, 169.0, 0, '5pct', 'SET50', '2022-12-22'],
 ['B', 'CPNREIT', 5000, 10.2, 1, '5pct', 'SET', '2023-05-23'],
 ['B', 'DIF', 2000, 10.3, 1, '5pct', 'SET', '2023-05-15'],
 ['B', 'EA', 400, 61.0, 0, '52WL', 'SET50', '2022-12-22'],
 ['B', 'JMART', 1200, 17.0, 0, '5pct', 'SET50', '2023-04-11'],
 ['B', 'JMT', 1800, 51.0, 0, '5pct', 'SET50', '2023-04-11'],
 ['B', 'KKP', 500, 58.0, 1, nan, 'SET100', '2023-04-28'],
 ['B', 'KTB', 1500, 14.3, 0, nan, 'SET50', '2023-04-20'],
 ['B', 'LANNA', 1500, 13.8, 0, nan, 'SET', '2023-03-18'],
 ['B', 'MCS', 3000, 7.0, 1, 'RD50pct', 'SET', '2023-03-17'],
 ['B', 'NER', 5000, 4.54, 1, 'RD40pct', 'SET', '2023-04-20'],
 ['B', 'ORI', 3000, 10.0, 1, '52WL', 'SET100', '2023-05-08'],
 ['B', 'PTG', 1800, 11.4, 1, nan, 'SET100', '2022-12-22'],
 ['B', 'PTTEP', 200, 134.5, 0, nan, 'SET50', '2023-02-14'],
 ['B', 'SINGER', 2000, 10.4, 1, 'RD60pct', 'SET100', '2023-05-03'],
 ['B', 'STA', 1200, 18.3, 0, 'RD50pct', 'SET100', '2023-04-19'],
 ['B', 'SYNEX', 3000, 12.5, 1, 'RND55pct', 'SET', '2023-03-09'],
 ['B', 'TASCO', 1500, 15.6, 0, 'XXX', 'SET', '2022-12-22'],
 ['B', 'TFFIF', 10000, 7.65, 1, 'DOS', 'SET', '2023-05-31'],
 ['B', 'TMT', 3000, 7.6, 1, 'RD25pct', 'SET', '2023-04-18'],
 ['B', 'TTB', 20000, 1.09, 0, '52WL', 'SET50', '2023-04-18'],
 ['S', 'AH', 1200, 39.0, 0, '5pct', 'SET', '2022-12-22'],
 ['S', 'AWC', 9000, 5.2, 0, '5pct', 'SET50', '2022-12-22'],
 ['S', 'BCH', 3000, 22.4, 0, '5pct', 'SET100', '2023-05-09'],
 ['S', 'GVREIT', 10000, 9.1, 0, '5pct', 'SET', '2023-05-26'],
 ['S', 'ICHI', 1500, 15.0, 1, '5pct', 'SET', '2022-12-22'],
 ['S', 'IVL', 2400, 37.75, 0, '5pct', 'SET50', '2023-05-26'],
 ['S', 'JASIF', 10000, 7.5, 1, 'CUT', 'SET', '2023-05-19'],
 ['S', 'KTC', 900, 52.5, 1, '5pct', 'SET50', '2022-12-22'],
 ['S', 'PTTGC', 600, 53.25, 0, 'RD45pct', 'SET50', '2023-02-27'],
 ['S', 'SENA', 15000, 4.5, 0, 'C4.48', 'SET', '2023-05-11']]

In [17]:
for rcd in rcds:
    print(rcd)

['B', 'BANPU', 3000, 7.8, 0, 'RD30pct', 'SET50', '2023-04-10']
['B', 'BBL', 200, 125.0, 0, nan, 'SET50', '2023-04-21']
['B', 'BDMS', 1000, 24.0, 0, 'XXX', 'SET50', '2022-12-22']
['B', 'BEM', 2500, 7.8, 0, '52WL', 'SET50', '2022-12-22']
['B', 'BH', 200, 169.0, 0, '5pct', 'SET50', '2022-12-22']
['B', 'CPNREIT', 5000, 10.2, 1, '5pct', 'SET', '2023-05-23']
['B', 'DIF', 2000, 10.3, 1, '5pct', 'SET', '2023-05-15']
['B', 'EA', 400, 61.0, 0, '52WL', 'SET50', '2022-12-22']
['B', 'JMART', 1200, 17.0, 0, '5pct', 'SET50', '2023-04-11']
['B', 'JMT', 1800, 51.0, 0, '5pct', 'SET50', '2023-04-11']
['B', 'KKP', 500, 58.0, 1, nan, 'SET100', '2023-04-28']
['B', 'KTB', 1500, 14.3, 0, nan, 'SET50', '2023-04-20']
['B', 'LANNA', 1500, 13.8, 0, nan, 'SET', '2023-03-18']
['B', 'MCS', 3000, 7.0, 1, 'RD50pct', 'SET', '2023-03-17']
['B', 'NER', 5000, 4.54, 1, 'RD40pct', 'SET', '2023-04-20']
['B', 'ORI', 3000, 10.0, 1, '52WL', 'SET100', '2023-05-08']
['B', 'PTG', 1800, 11.4, 1, nan, 'SET100', '2022-12-22']
['B', 'PTTEP', 200, 134.5, 0, nan, 'SET50', '2023-02-14']
['B', 'SINGER', 2000, 10.4, 1, 'RD60pct', 'SET100', '2023-05-03']
['B', 'STA', 1200, 18.3, 0, 'RD50pct', 'SET100', '2023-04-19']
['B', 'SYNEX', 3000, 12.5, 1, 'RND55pct', 'SET', '2023-03-09']
['B', 'TASCO', 1500, 15.6, 0, 'XXX', 'SET', '2022-12-22']
['B', 'TFFIF', 10000, 7.65, 1, 'DOS', 'SET', '2023-05-31']
['B', 'TMT', 3000, 7.6, 1, 'RD25pct', 'SET', '2023-04-18']
['B', 'TTB', 20000, 1.09, 0, '52WL', 'SET50', '2023-04-18']
['S', 'AH', 1200, 39.0, 0, '5pct', 'SET', '2022-12-22']
['S', 'AWC', 9000, 5.2, 0, '5pct', 'SET50', '2022-12-22']
['S', 'BCH', 3000, 22.4, 0, '5pct', 'SET100', '2023-05-09']
['S', 'GVREIT', 10000, 9.1, 0, '5pct', 'SET', '2023-05-26']
['S', 'ICHI', 1500, 15.0, 1, '5pct', 'SET', '2022-12-22']
['S', 'IVL', 2400, 37.75, 0, '5pct', 'SET50', '2023-05-26']
['S', 'JASIF', 10000, 7.5, 1, 'CUT', 'SET', '2023-05-19']
['S', 'KTC', 900, 52.5, 1, '5pct', 'SET50', '2022-12-22']
['S', 'PTTGC', 600, 53.25, 0, 'RD45pct', 'SET50', '2023-02-27']
['S', 'SENA', 15000, 4.5, 0, 'C4.48', 'SET', '2023-05-11']

In [18]:
sql = """
INSERT INTO orders (trade, name, qty, price, active, reason, market, xdate)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
"""
print(sql)

INSERT INTO orders (trade, name, qty, price, active, reason, market, xdate)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)

In [19]:
for rcd in rcds:
    conlite.execute(sql, rcd)

In [20]:
sql = '''
SELECT *
FROM orders
ORDER BY trade, name'''
df_orders = pd.read_sql(sql, conlite)
df_tab = pn.widgets.Tabulator(df_orders, layout='fit_data', width=800)
df_tab

Tabulator(layout='fit_data', value=    id trade  ..., width=800)

In [21]:
df_orders.query('active == 0')

    id trade    name    qty   price  active   reason  market       xdate
0    1     B   BANPU   3000    7.80       0  RD30pct   SET50  2023-04-10
1    2     B     BBL    200  125.00       0     None   SET50  2023-04-21
2    3     B    BDMS   1000   24.00       0      XXX   SET50  2022-12-22
3    4     B     BEM   2500    7.80       0     52WL   SET50  2022-12-22
4    5     B      BH    200  169.00       0     5pct   SET50  2022-12-22
7    8     B      EA    400   61.00       0     52WL   SET50  2022-12-22
8    9     B   JMART   1200   17.00       0     5pct   SET50  2023-04-11
9   10     B     JMT   1800   51.00       0     5pct   SET50  2023-04-11
11  12     B     KTB   1500   14.30       0     None   SET50  2023-04-20
12  13     B   LANNA   1500   13.80       0     None     SET  2023-03-18
17  18     B   PTTEP    200  134.50       0     None   SET50  2023-02-14
19  20     B     STA   1200   18.30       0  RD50pct  SET100  2023-04-19
21  22     B   TASCO   1500   15.60       0      XXX     SET  2022-12-22
24  25     B     TTB  20000    1.09       0     52WL   SET50  2023-04-18
25  26     S      AH   1200   39.00       0     5pct     SET  2022-12-22
26  27     S     AWC   9000    5.20       0     5pct   SET50  2022-12-22
27  28     S     BCH   3000   22.40       0     5pct  SET100  2023-05-09
28  29     S  GVREIT  10000    9.10       0     5pct     SET  2023-05-26
30  31     S     IVL   2400   37.75       0     5pct   SET50  2023-05-26
33  34     S   PTTGC    600   53.25       0  RD45pct   SET50  2023-02-27
34  35     S    SENA  15000    4.50       0    C4.48     SET  2023-05-11

In [22]:
cols = 'trade name qty price active reason market xdate'.split()
file_name = 'orders.csv'
data_file = data_path + file_name
output_file = csv_path + file_name
box_file = box_path + file_name
one_file = one_path + file_name
osd_file = osd_path + file_name

df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(output_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(data_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(box_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(one_file, header=True, index=False)
df_orders[cols].sort_values(['trade','name'],ascending=[True,True]).to_csv(osd_file, header=True, index=False)

In [23]:
df_orders.shape

(35, 9)