In [5]:
import pandas as pd

In [1]:
df = pd.DataFrame(json_data)
df

,date,symbol,securityType,adjustedPriceFlag,prior,open,high,low,close,average,...,trVolume,trValue,totalVolume,totalValue,pe,pbv,bvps,dividendYield,marketCap,volumeTurnover
0,2023-01-31,KCE,CS,Y,50,50.5,55.5,50.5,54.75,53.621031,...,15900,870525,104238878,5.589416e+09,25.7,5.02,10.9,2.92,64712616381,8.819367

In [2]:
df.dtypes

date                  object
symbol                object
securityType          object
adjustedPriceFlag     object
prior                  int64
open                 float64
high                 float64
low                  float64
close                float64
average              float64
aomVolume              int64
aomValue               int64
trVolume               int64
trValue                int64
totalVolume            int64
totalValue           float64
pe                   float64
pbv                  float64
bvps                 float64
dividendYield        float64
marketCap              int64
volumeTurnover       float64
dtype: object

In [4]:
cols = 'symbol date close high low totalVolume open'.split()
df[cols]

  symbol        date  close  high   low  totalVolume  open
0    KCE  2023-01-31  54.75  55.5  50.5    104238878  50.5

In [7]:
U1 = "https://www.setsmart.com/api/listed-company-api/eod-price-by-symbol?symbol=KCE&startDate=2023-01-31&endDate=2023-01-31&adjustedPriceFlag=N"
U1

'https://www.setsmart.com/api/listed-company-api/eod-price-by-symbol?symbol=KCE&startDate=2023-01-31&endDate=2023-01-31&adjustedPriceFlag=N'

In [9]:
key = '40ace8d4-508b-4350-ba3c-970deacab5d9'
key

'40ace8d4-508b-4350-ba3c-970deacab5d9'

In [10]:
url = U1 + '&api-key=' + key
url

'https://www.setsmart.com/api/listed-company-api/eod-price-by-symbol?symbol=KCE&startDate=2023-01-31&endDate=2023-01-31&adjustedPriceFlag=N&api-key=40ace8d4-508b-4350-ba3c-970deacab5d9'

In [28]:
df = pd.read_json(url)

HTTPError: HTTP Error 400:

In [16]:
data = curl -X GET "https://www.setsmart.com/api/listed-company-api/eod-price-by-security-type?securityType=CS&adjustedPriceFlag=N&api-key=40ace8d4-508b-4350-ba3c-970deacab5d9"

SyntaxError: invalid syntax (Temp/ipykernel_18704/1271497687.py, line 1)

In [29]:
!curl "https://www.setsmart.com/api/listed-company-api/eod-price-by-symbol?symbol=KCE&startDate=2023-01-31&endDate=2023-01-31&adjustedPriceFlag=N&api-key=40ace8d4-508b-4350-ba3c-970deacab5d9"

{"timestamp":"2023-02-01T07:56:10.441+0000","status":"fail","message":null,"detail":""}

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    87    0    87    0     0    248      0 --:--:-- --:--:-- --:--:--   249

In [34]:
df = pd.read_excel("data.xlsx", header=8)
df

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,ADVANC,-,196.00,1.00,0.512821,196.00,197.00,196.00,0,0.0000,1932624,3.793054e+05,9800,ATO,186.5,24000
1,AOT,-,74.00,-0.25,-0.336700,74.75,74.75,74.00,0,0.0000,6013781,4.467385e+05,155800,ATO,ATO,49800
2,AWC,-,5.85,-0.10,-1.680672,5.95,6.00,5.75,0,0.0000,78360219,4.571367e+05,217100,ATO,ATO,71200
3,BANPU,-,11.50,-0.10,-0.862069,11.50,11.70,11.50,0,0.0000,34733741,4.013776e+05,210100,ATO,ATO,467200
4,BBL,-,159.50,1.00,0.630915,160.00,160.00,158.00,62000,9827.0000,4181622,6.650630e+05,27800,ATO,ATO,5800
5,BDMS,-,30.25,0.50,1.680672,29.50,30.25,29.50,0,0.0000,20453922,6.114169e+05,59000,ATO,ATO,206700
6,BEM,-,9.75,0.05,0.515464,9.75,9.80,9.65,0,0.0000,20044421,1.944323e+05,23900,ATO,ATO,34300
7,BGRIM,-,40.75,0.50,1.242236,40.25,40.75,40.25,0,0.0000,1402985,5.688310e+04,30500,ATO,ATO,26300
8,BH,-,219.00,2.00,0.921659,217.00,220.00,217.00,0,0.0000,1842857,4.024637e+05,4500,ATO,ATO,2000
9,BTS,-,8.50,0.05,0.591716,8.45,8.50,8.40,0,0.0000,12513128,1.057666e+05,34000,ATO,ATO,20000
10,CBG,-,103.50,0.50,0.485437,103.50,104.00,102.50,0,0.0000,1134368,1.169271e+05,9700,ATO,ATO,1100
11,CENTEL,-,52.00,0.00,0.000000,52.25,52.25,51.50,0,0.0000,504550,2.614835e+04,5700,ATO,ATO,12000
12,COM7,-,32.25,1.00,3.200000,31.25,32.75,31.00,0,0.0000,13080911,4.185725e+05,33000,ATO,ATO,35800
13,CPALL,-,67.25,0.75,1.127820,66.75,67.25,66.50,3485700,232670.4750,22714328,1.516653e+06,49500,ATO,ATO,69400
14,CPF,-,23.90,0.30,1.271186,23.60,24.00,23.60,0,0.0000,15549500,3.710089e+05,17200,ATO,ATO,51300
15,CPN,-,71.75,0.50,0.701754,72.25,72.25,71.50,0,0.0000,2099096,1.509533e+05,51900,ATO,ATO,4500
16,CRC,-,43.50,1.00,2.352941,42.75,43.50,42.75,0,0.0000,3123472,1.350321e+05,114800,ATO,ATO,42100
17,DELTA,-,908.00,8.00,0.888889,906.00,918.00,904.00,0,0.0000,1125793,1.024631e+06,6600,ATO,ATO,900
18,DTAC,-,49.75,0.25,0.505051,49.25,49.75,49.00,0,0.0000,5412223,2.672927e+05,2400,ATO,ATO,1000
19,EA,-,87.75,1.25,1.445087,86.50,88.00,86.50,40000,3520.0000,7719931,6.758843e+05,25100,ATO,ATO,3800
20,EGCO,-,174.00,0.00,0.000000,174.00,175.50,173.50,0,0.0000,211145,3.678185e+04,600,ATO,122,100
21,GLOBAL,-,20.90,0.10,0.480769,20.90,21.10,20.80,0,0.0000,3578721,7.499927e+04,17000,ATO,ATO,57200
22,GPSC,-,69.50,0.75,1.090909,69.00,69.75,68.75,0,0.0000,2216573,1.541030e+05,9500,ATO,ATO,16100
23,GULF,-,54.00,0.25,0.465116,54.00,54.25,53.75,0,0.0000,5126946,2.768747e+05,35400,ATO,ATO,9700
24,HMPRO,-,14.60,0.30,2.097902,14.40,14.70,14.30,0,0.0000,10335729,1.502297e+05,69000,ATO,ATO,34300
25,INTUCH,-,73.25,0.50,0.687285,72.50,73.75,72.50,0,0.0000,791380,5.794813e+04,3400,ATO,ATO,10500
26,IVL,-,41.25,0.75,1.851852,40.50,41.25,40.50,0,0.0000,5807169,2.378571e+05,3300,ATO,ATO,132800
27,JMART,-,37.75,0.50,1.342282,37.50,38.00,37.25,0,0.0000,2305133,8.668515e+04,4700,ATO,ATO,10400
28,JMT,-,54.25,0.75,1.401869,54.00,54.50,53.00,0,0.0000,8136288,4.370957e+05,1600,ATO,ATO,10900
29,KBANK,-,145.00,0.00,0.000000,145.00,146.00,144.00,170000,24565.0000,9241612,1.337902e+06,33900,ATO,ATO,38500
30,KTB,-,17.70,0.20,1.142857,17.60,17.70,17.50,0,0.0000,19835670,3.491151e+05,166000,ATO,ATO,113300
31,KTC,-,58.00,1.50,2.654867,56.75,58.25,56.50,0,0.0000,6387180,3.676835e+05,2600,ATO,ATO,500
32,LH,-,9.90,0.00,0.000000,9.90,9.95,9.85,0,0.0000,11179431,1.105949e+05,61700,ATO,ATO,7100
33,MINT,-,33.00,-0.25,-0.751880,33.50,33.50,33.00,0,0.0000,2233739,7.426662e+04,554100,ATO,ATO,677100
34,MTC,-,38.75,1.25,3.333333,37.75,38.75,37.50,0,0.0000,7960961,3.035649e+05,85700,ATO,ATO,53500
35,OR,-,22.40,0.00,0.000000,22.40,22.50,22.30,0,0.0000,9103176,2.038630e+05,21500,ATO,ATO,15700
36,OSP,-,28.50,0.50,1.785714,28.00,28.50,28.00,0,0.0000,1521505,4.295337e+04,5200,ATO,ATO,30200
37,PTT,-,33.25,0.00,0.000000,33.25,33.50,33.00,0,0.0000,19603332,6.513455e+05,39500,ATO,ATO,20300
38,PTTEP,-,172.50,1.00,0.583090,172.00,173.50,172.00,0,0.0000,3301962,5.707909e+05,31800,ATO,ATO,4600
39,PTTGC,-,49.75,0.50,1.015228,49.25,50.00,49.25,0,0.0000,7193753,3.585802e+05,45100,ATO,ATO,8700
40,RATCH,-,42.75,0.50,1.183432,42.25,42.75,42.25,0,0.0000,2651990,1.127015e+05,2800,ATO,ATO,31700
41,SCB,-,104.50,0.50,0.480769,104.50,105.00,104.00,155000,16120.0000,3104522,3.255403e+05,47200,ATO,ATO,1400
42,SCC,-,339.00,3.00,0.892857,337.00,341.00,337.00,383600,128889.6000,916414,3.096761e+05,6100,ATO,ATO,900
43,SCGP,-,53.25,1.00,1.913876,52.75,53.25,52.50,58294,3045.8615,4241883,2.248145e+05,83200,ATO,ATO,12300
44,TIDLOR,-,28.50,0.75,2.702703,27.75,28.50,27.50,0,0.0000,5218280,1.460941e+05,82100,ATO,ATO,42100
45,TISCO,-,102.00,-0.50,-0.487805,103.00,103.00,102.00,80000,8200.0000,1212333,1.241122e+05,10500,ATO,ATO,10300
46,TOP,-,58.50,0.75,1.298701,58.00,59.00,58.00,0,0.0000,5950188,3.488177e+05,34500,ATO,55.75,16600
47,TRUE,-,4.88,0.02,0.411523,4.88,4.90,4.86,0,0.0000,4936855,2.410203e+04,16500,ATO,ATO,9000
48,TTB,-,1.46,-0.01,-0.680272,1.47,1.48,1.45,0,0.0000,119247195,1.743869e+05,633300,ATO,ATO,261700
49,TU,-,16.10,0.10,0.625000,16.00,16.20,15.90,0,0.0000,5039520,8.100342e+04,9500,ATO,ATO,100

In [37]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df[cols]

    Symbol    Last    High     Low  Total-Volume    Open
0   ADVANC  196.00  197.00  196.00       1932624  196.00
1      AOT   74.00   74.75   74.00       6013781   74.75
2      AWC    5.85    6.00    5.75      78360219    5.95
3    BANPU   11.50   11.70   11.50      34733741   11.50
4      BBL  159.50  160.00  158.00       4181622  160.00
5     BDMS   30.25   30.25   29.50      20453922   29.50
6      BEM    9.75    9.80    9.65      20044421    9.75
7    BGRIM   40.75   40.75   40.25       1402985   40.25
8       BH  219.00  220.00  217.00       1842857  217.00
9      BTS    8.50    8.50    8.40      12513128    8.45
10     CBG  103.50  104.00  102.50       1134368  103.50
11  CENTEL   52.00   52.25   51.50        504550   52.25
12    COM7   32.25   32.75   31.00      13080911   31.25
13   CPALL   67.25   67.25   66.50      22714328   66.75
14     CPF   23.90   24.00   23.60      15549500   23.60
15     CPN   71.75   72.25   71.50       2099096   72.25
16     CRC   43.50   43.50   42.75       3123472   42.75
17   DELTA  908.00  918.00  904.00       1125793  906.00
18    DTAC   49.75   49.75   49.00       5412223   49.25
19      EA   87.75   88.00   86.50       7719931   86.50
20    EGCO  174.00  175.50  173.50        211145  174.00
21  GLOBAL   20.90   21.10   20.80       3578721   20.90
22    GPSC   69.50   69.75   68.75       2216573   69.00
23    GULF   54.00   54.25   53.75       5126946   54.00
24   HMPRO   14.60   14.70   14.30      10335729   14.40
25  INTUCH   73.25   73.75   72.50        791380   72.50
26     IVL   41.25   41.25   40.50       5807169   40.50
27   JMART   37.75   38.00   37.25       2305133   37.50
28     JMT   54.25   54.50   53.00       8136288   54.00
29   KBANK  145.00  146.00  144.00       9241612  145.00
30     KTB   17.70   17.70   17.50      19835670   17.60
31     KTC   58.00   58.25   56.50       6387180   56.75
32      LH    9.90    9.95    9.85      11179431    9.90
33    MINT   33.00   33.50   33.00       2233739   33.50
34     MTC   38.75   38.75   37.50       7960961   37.75
35      OR   22.40   22.50   22.30       9103176   22.40
36     OSP   28.50   28.50   28.00       1521505   28.00
37     PTT   33.25   33.50   33.00      19603332   33.25
38   PTTEP  172.50  173.50  172.00       3301962  172.00
39   PTTGC   49.75   50.00   49.25       7193753   49.25
40   RATCH   42.75   42.75   42.25       2651990   42.25
41     SCB  104.50  105.00  104.00       3104522  104.50
42     SCC  339.00  341.00  337.00        916414  337.00
43    SCGP   53.25   53.25   52.50       4241883   52.75
44  TIDLOR   28.50   28.50   27.50       5218280   27.75
45   TISCO  102.00  103.00  102.00       1212333  103.00
46     TOP   58.50   59.00   58.00       5950188   58.00
47    TRUE    4.88    4.90    4.86       4936855    4.88
48     TTB    1.46    1.48    1.45     119247195    1.47
49      TU   16.10   16.20   15.90       5039520   16.00

In [38]:
df.insert(1, 'Date', '2023-02-01')
colt = 'Symbol Date Last High Low Total-Volume Open'.split()
df[colt]

    Symbol        Date    Last    High     Low  Total-Volume    Open
0   ADVANC  2023-02-01  196.00  197.00  196.00       1932624  196.00
1      AOT  2023-02-01   74.00   74.75   74.00       6013781   74.75
2      AWC  2023-02-01    5.85    6.00    5.75      78360219    5.95
3    BANPU  2023-02-01   11.50   11.70   11.50      34733741   11.50
4      BBL  2023-02-01  159.50  160.00  158.00       4181622  160.00
5     BDMS  2023-02-01   30.25   30.25   29.50      20453922   29.50
6      BEM  2023-02-01    9.75    9.80    9.65      20044421    9.75
7    BGRIM  2023-02-01   40.75   40.75   40.25       1402985   40.25
8       BH  2023-02-01  219.00  220.00  217.00       1842857  217.00
9      BTS  2023-02-01    8.50    8.50    8.40      12513128    8.45
10     CBG  2023-02-01  103.50  104.00  102.50       1134368  103.50
11  CENTEL  2023-02-01   52.00   52.25   51.50        504550   52.25
12    COM7  2023-02-01   32.25   32.75   31.00      13080911   31.25
13   CPALL  2023-02-01   67.25   67.25   66.50      22714328   66.75
14     CPF  2023-02-01   23.90   24.00   23.60      15549500   23.60
15     CPN  2023-02-01   71.75   72.25   71.50       2099096   72.25
16     CRC  2023-02-01   43.50   43.50   42.75       3123472   42.75
17   DELTA  2023-02-01  908.00  918.00  904.00       1125793  906.00
18    DTAC  2023-02-01   49.75   49.75   49.00       5412223   49.25
19      EA  2023-02-01   87.75   88.00   86.50       7719931   86.50
20    EGCO  2023-02-01  174.00  175.50  173.50        211145  174.00
21  GLOBAL  2023-02-01   20.90   21.10   20.80       3578721   20.90
22    GPSC  2023-02-01   69.50   69.75   68.75       2216573   69.00
23    GULF  2023-02-01   54.00   54.25   53.75       5126946   54.00
24   HMPRO  2023-02-01   14.60   14.70   14.30      10335729   14.40
25  INTUCH  2023-02-01   73.25   73.75   72.50        791380   72.50
26     IVL  2023-02-01   41.25   41.25   40.50       5807169   40.50
27   JMART  2023-02-01   37.75   38.00   37.25       2305133   37.50
28     JMT  2023-02-01   54.25   54.50   53.00       8136288   54.00
29   KBANK  2023-02-01  145.00  146.00  144.00       9241612  145.00
30     KTB  2023-02-01   17.70   17.70   17.50      19835670   17.60
31     KTC  2023-02-01   58.00   58.25   56.50       6387180   56.75
32      LH  2023-02-01    9.90    9.95    9.85      11179431    9.90
33    MINT  2023-02-01   33.00   33.50   33.00       2233739   33.50
34     MTC  2023-02-01   38.75   38.75   37.50       7960961   37.75
35      OR  2023-02-01   22.40   22.50   22.30       9103176   22.40
36     OSP  2023-02-01   28.50   28.50   28.00       1521505   28.00
37     PTT  2023-02-01   33.25   33.50   33.00      19603332   33.25
38   PTTEP  2023-02-01  172.50  173.50  172.00       3301962  172.00
39   PTTGC  2023-02-01   49.75   50.00   49.25       7193753   49.25
40   RATCH  2023-02-01   42.75   42.75   42.25       2651990   42.25
41     SCB  2023-02-01  104.50  105.00  104.00       3104522  104.50
42     SCC  2023-02-01  339.00  341.00  337.00        916414  337.00
43    SCGP  2023-02-01   53.25   53.25   52.50       4241883   52.75
44  TIDLOR  2023-02-01   28.50   28.50   27.50       5218280   27.75
45   TISCO  2023-02-01  102.00  103.00  102.00       1212333  103.00
46     TOP  2023-02-01   58.50   59.00   58.00       5950188   58.00
47    TRUE  2023-02-01    4.88    4.90    4.86       4936855    4.88
48     TTB  2023-02-01    1.46    1.48    1.45     119247195    1.47
49      TU  2023-02-01   16.10   16.20   15.90       5039520   16.00

In [39]:
df_HD = pd.read_excel("StockQuotation (3).xlsx", header=8)
df_HD

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,ADVANC,-,198.00,3.00,1.538462,196.00,198.00,196.00,0,0.0,2730306,536589.17250,340500,197.50,198.00,129400
1,AP,-,12.20,0.30,2.521008,12.00,12.20,11.80,0,0.0,29432058,352949.44530,2441500,12.10,12.20,2083900
2,BBL,-,160.00,1.50,0.946372,160.00,160.00,158.00,62000,9827.0,4994969,794805.81600,413800,159.50,160.00,513800
3,BCH,-,21.60,-0.20,-0.917431,21.60,21.80,21.30,0,0.0,10671559,230301.28620,502900,21.60,21.70,905400
4,BCPG,-,9.95,0.10,1.015228,9.95,10.10,9.95,0,0.0,4605144,46056.23965,688800,9.95,10.00,587900
5,BTS,-,8.45,0.00,0.000000,8.45,8.50,8.40,0,0.0,13071616,110504.34855,4049300,8.45,8.50,2125500
6,CHG,-,4.00,0.00,0.000000,4.00,4.04,3.92,0,0.0,55318924,220823.85012,2923600,4.00,4.02,4863900
7,CPF,-,24.00,0.40,1.694915,23.60,24.00,23.60,0,0.0,16211355,386839.27310,2575100,23.90,24.00,3649400
8,EGCO,-,173.50,-0.50,-0.287356,174.00,175.50,173.50,0,0.0,365379,63615.27000,105600,173.50,174.00,82800
9,GUNKUL,-,5.00,0.02,0.401606,5.00,5.05,4.98,0,0.0,32124912,160765.03490,8247500,5.00,5.05,14373300
10,HANA,-,60.25,-0.25,-0.413223,60.25,61.25,59.75,0,0.0,8461192,512476.50400,346500,60.25,60.50,346600
11,INTUCH,-,73.50,0.75,1.030928,72.50,73.75,72.50,0,0.0,1003190,73494.01750,118700,73.25,73.50,45800
12,KKP,-,68.75,0.50,0.732601,68.50,69.00,68.25,100000,6825.0,3871502,265346.21025,240000,68.75,69.00,533700
13,KTB,-,17.60,0.10,0.571429,17.60,17.70,17.50,0,0.0,25537371,449460.91930,9120400,17.50,17.60,3548600
14,LH,-,9.95,0.05,0.505051,9.90,9.95,9.85,0,0.0,20863046,206502.06355,4075800,9.90,9.95,3549300
15,ORI,-,12.20,0.00,0.000000,12.20,12.20,12.00,0,0.0,4635867,56101.16290,358800,12.10,12.20,2410200
16,OSP,-,28.25,0.25,0.892857,28.00,28.50,28.00,0,0.0,1722724,48646.90950,510900,28.25,28.50,2873400
17,PTT,-,33.25,0.00,0.000000,33.25,33.50,33.00,0,0.0,21001307,697562.74825,16988000,33.00,33.25,9901700
18,PTTEP,-,173.00,1.50,0.874636,172.00,173.50,172.00,0,0.0,3978258,687599.37050,548400,172.50,173.00,400400
19,QH,-,2.36,0.00,0.000000,2.36,2.38,2.34,0,0.0,9490948,22351.44492,6786000,2.34,2.36,2626000
20,RATCH,-,43.00,0.75,1.775148,42.25,43.00,42.25,0,0.0,3416278,145375.28725,512400,42.75,43.00,541100
21,SAWAD,-,56.00,2.75,5.164319,53.50,56.00,53.50,0,0.0,13761685,760347.29625,470100,55.75,56.00,1152400
22,SCC,-,339.00,3.00,0.892857,337.00,341.00,337.00,383600,128889.6,1036991,350587.11700,80400,339.00,340.00,346400
23,SPALI,-,24.20,0.00,0.000000,24.30,24.40,24.00,0,0.0,5826301,140430.11290,456900,24.10,24.20,334700
24,TCAP,-,43.25,0.50,1.169591,43.00,43.50,42.50,500000,21250.0,2620074,112410.67400,469900,43.00,43.25,340500
25,THANI,-,4.14,0.04,0.975610,4.10,4.14,4.08,0,0.0,5713438,23519.06614,1390900,4.12,4.14,3801400
26,TISCO,-,102.50,0.00,0.000000,103.00,103.00,102.00,80000,8200.0,1334395,136621.43000,1074200,102.00,102.50,744900
27,TTB,-,1.45,-0.02,-1.360544,1.47,1.48,1.45,0,0.0,169032790,247073.13209,64840300,1.45,1.46,14204100
28,TU,-,16.10,0.10,0.625000,16.00,16.20,15.90,0,0.0,5753906,92544.43910,1999500,16.10,16.20,2365500
29,WHA,-,3.86,0.08,2.116402,3.82,3.88,3.80,0,0.0,77437202,297193.25136,2703900,3.84,3.86,8119300

In [41]:
df_HD.rename(columns={col: col.replace(" ", "-") for col in df_HD.columns}, inplace=True)
df_HD[cols]

    Symbol    Last    High     Low  Total-Volume    Open
0   ADVANC  198.00  198.00  196.00       2730306  196.00
1       AP   12.20   12.20   11.80      29432058   12.00
2      BBL  160.00  160.00  158.00       4994969  160.00
3      BCH   21.60   21.80   21.30      10671559   21.60
4     BCPG    9.95   10.10    9.95       4605144    9.95
5      BTS    8.45    8.50    8.40      13071616    8.45
6      CHG    4.00    4.04    3.92      55318924    4.00
7      CPF   24.00   24.00   23.60      16211355   23.60
8     EGCO  173.50  175.50  173.50        365379  174.00
9   GUNKUL    5.00    5.05    4.98      32124912    5.00
10    HANA   60.25   61.25   59.75       8461192   60.25
11  INTUCH   73.50   73.75   72.50       1003190   72.50
12     KKP   68.75   69.00   68.25       3871502   68.50
13     KTB   17.60   17.70   17.50      25537371   17.60
14      LH    9.95    9.95    9.85      20863046    9.90
15     ORI   12.20   12.20   12.00       4635867   12.20
16     OSP   28.25   28.50   28.00       1722724   28.00
17     PTT   33.25   33.50   33.00      21001307   33.25
18   PTTEP  173.00  173.50  172.00       3978258  172.00
19      QH    2.36    2.38    2.34       9490948    2.36
20   RATCH   43.00   43.00   42.25       3416278   42.25
21   SAWAD   56.00   56.00   53.50      13761685   53.50
22     SCC  339.00  341.00  337.00       1036991  337.00
23   SPALI   24.20   24.40   24.00       5826301   24.30
24    TCAP   43.25   43.50   42.50       2620074   43.00
25   THANI    4.14    4.14    4.08       5713438    4.10
26   TISCO  102.50  103.00  102.00       1334395  103.00
27     TTB    1.45    1.48    1.45     169032790    1.47
28      TU   16.10   16.20   15.90       5753906   16.00
29     WHA    3.86    3.88    3.80      77437202    3.82