In [7]:
import glob
import os
import pandas as pd
from datetime import date, timedelta
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

data_path = "../data/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"
dts_path = "/Users/User/Downloads/"


pd.options.display.max_rows = 50
pd.options.display.float_format = '{:.2f}'.format

today = date.today()
yesterday = today - timedelta(days=1)
today, yesterday

(datetime.date(2023, 7, 13), datetime.date(2023, 7, 12))

In [2]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2023-07-13
yesterday: 2023-07-12

### Restart & Run All Cells

In [3]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [4]:
file_name = "StockQuotation.xlsx"
input_file = dts_path + file_name
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['%Change'] != '-']
df_S100[colu].sort_values(['%Change'],ascending=[False])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
22,CBG,67.75,2.75,4.23,65.50,68.50,64.50,5041861,337518.06
47,IVL,34.00,1.00,3.03,33.00,34.00,33.00,6642889,222695.44
82,STA,17.10,0.50,3.01,16.80,17.20,16.60,2090456,35497.05
83,STEC,9.10,0.25,2.82,8.90,9.15,8.90,6077456,54968.52
42,GUNKUL,3.10,0.08,2.65,3.02,3.10,3.00,12505091,38074.51
...,...,...,...,...,...,...,...,...,...
0,AAV,2.52,-0.06,-2.33,2.58,2.58,2.50,31424862,79511.57
14,BDMS,27.25,-0.75,-2.68,28.00,28.25,27.25,41732521,1157412.18
30,CPN,63.25,-2.00,-3.07,65.00,65.00,63.25,6974040,445268.88
92,TLI,10.60,-0.40,-3.64,11.00,11.00,10.50,12296500,131778.84
23,CENTEL,43.50,-1.75,-3.87,45.00,45.50,43.25,3984883,177430.60

In [5]:
df_S100.query('Symbol == "PTG"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
66,PTG,-,10.30,-0.10,-0.96,10.30,10.40,10.10,0,0,9098979,93237.66,500,ATO,ATO,39800

In [8]:
file_name = "StockQuotation.xlsx"
input_file = dts_path + file_name
df_S50 = pd.read_excel(input_file, header=8)
df_S50 = df_S50[df_S50['%Change'] != '-']
df_S50[colu].sort_values(['Symbol'],ascending=[True])

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,ADVANC,218.00,1.00,0.46,218.00,219.00,217.00,2883544,628303.64
1,AOT,69.25,-2.00,-2.81,70.50,70.75,69.25,39163199,2742093.00
2,AWC,4.44,-0.06,-1.33,4.54,4.56,4.42,31712767,141912.41
3,BANPU,8.75,0.00,0.00,8.70,8.75,8.65,18933311,164947.63
4,BBL,156.50,-0.50,-0.32,157.00,157.00,155.50,5183275,810472.49
5,BDMS,27.75,-0.25,-0.89,28.00,28.25,27.25,56341387,1558892.29
6,BEM,8.45,0.10,1.20,8.35,8.45,8.30,6256033,52374.87
7,BGRIM,35.50,0.25,0.71,35.50,35.75,34.75,4873628,171923.76
8,BH,215.00,-3.00,-1.38,218.00,218.00,214.00,1261287,271941.84
9,BTS,7.55,0.00,0.00,7.55,7.60,7.50,6243601,47143.79
10,CBG,68.00,3.00,4.62,65.50,68.50,64.50,6069072,407102.19
11,CENTEL,44.25,-1.00,-2.21,45.00,45.50,43.25,5769925,255763.42
12,COM7,26.75,0.50,1.90,26.50,27.25,26.00,4945768,131868.68
13,CPALL,61.50,-1.00,-1.60,62.25,62.50,61.25,29382664,1808498.66
14,CPF,19.50,0.00,0.00,19.50,19.60,19.40,3172474,61715.26
15,CPN,64.00,-1.25,-1.92,65.00,65.00,63.25,8048540,513706.72
16,CRC,38.00,-0.50,-1.30,38.00,38.75,37.75,4866689,185776.84
17,DELTA,101.00,2.00,2.02,99.75,101.50,99.25,4820059,485311.57
18,EA,54.25,0.50,0.93,53.75,54.50,53.25,3293874,177200.65
19,EGCO,131.50,0.50,0.38,131.50,132.00,130.00,872364,114343.37
20,GLOBAL,15.50,0.30,1.97,15.40,15.60,15.30,3884268,59994.04
21,GPSC,53.25,0.25,0.47,53.25,53.75,53.00,6031542,322305.79
22,GULF,47.00,-0.25,-0.53,47.50,47.75,46.75,15440496,729637.44
23,HMPRO,13.80,0.10,0.73,13.80,13.80,13.60,7364554,100963.73
24,INTUCH,75.25,2.25,3.08,73.50,75.50,73.00,5006068,373434.72
25,IVL,34.25,1.25,3.79,33.00,34.50,33.00,10718262,362718.48
26,KBANK,131.50,1.00,0.77,130.50,132.00,130.00,7653454,1002125.14
27,KTB,19.60,0.20,1.03,19.30,19.60,19.20,47806985,929831.71
28,KTC,45.50,-0.75,-1.62,45.00,46.75,44.75,15438250,713183.25
29,LH,8.35,-0.05,-0.60,8.40,8.40,8.30,16810794,140415.11
30,MINT,32.25,0.00,0.00,32.00,32.50,31.00,23118002,736073.32
31,MTC,35.50,0.00,0.00,35.50,36.25,35.50,3280459,117406.01
32,OR,20.60,0.10,0.49,20.60,20.70,20.50,7136653,147225.61
33,OSP,27.75,0.00,0.00,27.50,27.75,27.50,2153275,59416.91
34,PTT,34.25,0.00,0.00,34.25,34.50,34.00,45395204,1554821.02
35,PTTEP,157.00,2.00,1.29,155.00,157.00,155.00,5128850,798935.71
36,PTTGC,39.50,0.50,1.28,39.00,39.75,38.50,4602464,180351.61
37,RATCH,35.50,0.25,0.71,35.25,35.50,35.00,884839,31237.76
38,SAWAD,45.75,1.00,2.23,44.50,46.25,44.50,4812290,219337.46
39,SCB,108.00,0.00,0.00,107.50,108.00,107.00,4133581,444824.55
40,SCC,324.00,-2.00,-0.61,326.00,327.00,323.00,1078299,349972.36
41,SCGP,37.50,0.25,0.67,37.25,37.75,37.00,3890173,145718.17
42,TIDLOR,22.40,0.10,0.45,22.40,22.60,22.10,14820681,331106.49
43,TISCO,96.50,0.50,0.52,96.50,97.25,96.25,5020469,485832.04
44,TLI,10.50,-0.50,-4.55,11.00,11.00,10.50,16160084,172656.41
45,TOP,46.00,0.75,1.66,45.25,46.00,44.75,4809719,219303.05
46,TRUE,6.60,0.10,1.54,6.55,6.70,6.50,31716503,209603.59
47,TTB,1.54,0.02,1.32,1.53,1.54,1.51,260544110,397329.40
48,TU,12.60,0.10,0.80,12.50,12.70,12.40,11525549,144849.78
49,WHA,4.74,-0.04,-0.84,4.78,4.78,4.66,70171423,330643.93

In [10]:
s100 = df_S100.merge(df_S50, on='Symbol', how='left',indicator=True)
s100

,Symbol,Trading Sign_x,Last_x,Change_x,%Change_x,Open_x,High_x,Low_x,TR Volume_x,TR Value (k)_x,...,Low_y,TR Volume_y,TR Value (k)_y,Total Volume_y,Total Value (k)_y,Bid Size_y,Bid_y,Offer_y,Offer Size_y,_merge
0,AAV,-,2.52,-0.06,-2.33,2.58,2.58,2.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,ACE,-,1.81,0.00,0.00,1.82,1.82,1.77,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,ADVANC,-,217.00,0.00,0.00,218.00,219.00,217.00,0,0,...,217.00,0.00,0.00,2883544.00,628303.64,264900.00,218.00,219.00,903700.00,both
3,AMATA,-,21.90,-0.30,-1.35,22.20,22.20,21.80,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,AOT,-,69.75,-1.50,-2.11,70.50,70.75,69.50,0,0,...,69.25,0.00,0.00,39163199.00,2742093.00,2010500.00,69.25,69.50,1638300.00,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,TRUE,-,6.55,0.05,0.77,6.55,6.70,6.50,0,0,...,6.50,0.00,0.00,31716503.00,209603.59,4885900.00,6.55,6.60,1018500.00,both
96,TTB,-,1.52,0.00,0.00,1.53,1.54,1.51,0,0,...,1.51,0.00,0.00,260544110.00,397329.40,51599000.00,1.53,1.54,52761200.00,both
97,TU,-,12.50,0.00,0.00,12.50,12.70,12.40,0,0,...,12.40,0.00,0.00,11525549.00,144849.78,4021100.00,12.50,12.60,2544700.00,both
98,VGI,-,2.74,-0.02,-0.72,2.76,2.80,2.72,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
99,WHA,-,4.70,-0.08,-1.67,4.78,4.78,4.68,0,0,...,4.66,0.00,0.00,70171423.00,330643.93,2330900.00,4.72,4.74,4344500.00,both

In [13]:
s100[s100['_merge'] == 'left_only']

,Symbol,Trading Sign_x,Last_x,Change_x,%Change_x,Open_x,High_x,Low_x,TR Volume_x,TR Value (k)_x,...,Low_y,TR Volume_y,TR Value (k)_y,Total Volume_y,Total Value (k)_y,Bid Size_y,Bid_y,Offer_y,Offer Size_y,_merge
0,AAV,-,2.52,-0.06,-2.33,2.58,2.58,2.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,ACE,-,1.81,0.00,0.00,1.82,1.82,1.77,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,AMATA,-,21.90,-0.30,-1.35,22.20,22.20,21.80,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,AP,-,11.30,0.20,1.80,11.10,11.30,11.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
6,AURA,-,14.90,0.00,0.00,15.00,15.00,14.80,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8,BAM,-,10.30,0.10,0.98,10.20,10.40,10.10,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
11,BCH,-,17.10,-0.10,-0.58,17.10,17.30,17.10,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
12,BCP,-,38.25,0.00,0.00,38.25,38.25,37.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
13,BCPG,-,8.95,0.00,0.00,9.00,9.00,8.90,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
18,BLA,-,23.30,-0.40,-1.69,23.60,23.60,23.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
19,BTG,-,25.75,0.50,1.98,25.25,25.75,25.25,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
21,BYD,-,5.65,0.00,0.00,5.65,5.70,5.45,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
24,CHG,-,2.90,-0.02,-0.68,2.92,2.94,2.88,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
25,CK,-,20.00,0.00,0.00,19.80,20.00,19.80,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
26,CKP,-,3.42,0.02,0.59,3.36,3.44,3.36,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
33,DOHOME,-,8.80,0.05,0.57,8.85,8.95,8.65,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
36,ERW,-,4.36,0.04,0.93,4.28,4.38,4.26,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
37,ESSO,-,9.20,-0.05,-0.54,9.20,9.25,9.15,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
38,FORTH,-,25.75,0.50,1.98,25.50,26.25,25.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
42,GUNKUL,-,3.10,0.08,2.65,3.02,3.10,3.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
43,HANA,-,44.00,1.00,2.33,43.75,44.50,43.25,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
46,IRPC,-,2.30,0.00,0.00,2.30,2.32,2.28,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
48,JMART,-,15.70,0.30,1.95,15.60,16.10,15.40,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
49,JMT,-,33.50,0.50,1.52,33.50,34.75,33.25,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
51,KCE,-,36.50,0.50,1.39,36.00,36.75,35.75,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
52,KKP,-,59.25,0.00,0.00,59.25,59.50,59.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
56,MBK,-,15.50,-0.10,-0.64,15.50,15.80,15.40,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
57,MEGA,-,38.50,0.50,1.32,38.00,38.75,38.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
60,NEX,-,9.70,0.10,1.04,9.60,9.80,9.45,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
62,ORI,-,10.10,0.00,0.00,10.10,10.20,10.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
64,PLANB,-,7.80,0.10,1.30,7.70,7.85,7.65,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
65,PSL,-,9.50,0.20,2.15,9.45,9.60,9.40,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
66,PTG,-,10.30,-0.10,-0.96,10.30,10.40,10.10,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
71,RCL,-,23.70,0.10,0.42,23.70,23.90,23.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
72,SABUY,-,8.25,0.00,0.00,8.25,8.30,8.15,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
77,SIRI,-,1.85,-0.02,-1.07,1.86,1.87,1.84,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
78,SJWD,-,15.20,0.20,1.33,15.00,15.20,14.90,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
79,SNNP,-,22.20,-0.10,-0.45,22.40,22.60,22.10,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
80,SPALI,-,20.30,0.00,0.00,20.30,20.30,20.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
81,SPRC,-,8.00,0.00,0.00,8.00,8.10,7.95,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
82,STA,-,17.10,0.50,3.01,16.80,17.20,16.60,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
83,STEC,-,9.10,0.25,2.82,8.90,9.15,8.90,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
84,STGT,-,7.20,0.00,0.00,7.25,7.25,7.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
85,TASCO,-,17.60,-0.10,-0.56,17.70,17.70,17.60,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
86,TCAP,-,47.75,-0.25,-0.52,47.75,48.00,47.50,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
87,THANI,-,3.22,0.02,0.62,3.22,3.24,3.20,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
88,THG,-,65.75,0.50,0.77,65.50,66.00,65.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
90,TIPH,-,41.25,0.50,1.23,40.75,41.25,40.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
94,TQM,-,25.25,0.25,1.00,25.00,25.50,25.00,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
98,VGI,-,2.74,-0.02,-0.72,2.76,2.80,2.72,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only